version: "3.7"

services:
  battle-snack-1:
    build: .
    environment:
      PORT: "8001"
      SNAKE: "BATTLE"
    ports:
      - "8001:8001"
    container_name: battle-snack-1
    restart: always

  battle-snack-2:
    build: .
    environment:
      PORT: "8002"
      SNAKE: "SOLO"
    ports:
      - "8002:8002"
    container_name: battle-snack-2
    restart: always

  battle-snack-3:
    build: .
    environment:
      PORT: "8003"
      SNAKE: "HUNGRY"
    ports:
      - "8003:8003"
    container_name: battle-snack-3
    restart: always

